name: Unit Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
concurrency:
  group: lv2020
  cancel-in-progress: false
jobs:
  checkout:
    runs-on: lv2020
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  test:
    needs: checkout
    runs-on: lv2020
    steps:
      - uses: astemes/astemes-github-actions/runLUnit@main
        with:
          project-path: "tests"